# Generated by Django 6.0.7 on 2026-07-15 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='提现单号')),
                ('channel', models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝')], max_length=20, verbose_name='提现渠道')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('await_confirm', '待用户确认'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('payee_account', models.CharField(max_length=128, verbose_name='收款账号')),
                ('payee_name', models.CharField(max_length=64, verbose_name='收款人姓名')),
                ('provider_trade_no', models.CharField(blank=True, default='', max_length=128, verbose_name='第三方单号')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='第三方返回')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现订单',
                'verbose_name_plural': '提现订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝')], max_length=20, verbose_name='渠道')),
                ('account', models.CharField(max_length=128, verbose_name='收款账号')),
                ('account_name', models.CharField(max_length=64, verbose_name='收款人姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收款账户',
                'verbose_name_plural': '收款账户',
                'ordering': ['channel', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='uniq_payee_user_channel')],
            },
        ),
    ]
