# Generated by Django 6.0.7 on 2026-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实名认证时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False, verbose_name='已实名认证'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名'),
        ),
    ]
