# Generated by Django 6.0.7 on 2026-07-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_identity_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刷脸认证时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_face_verified',
            field=models.BooleanField(default=False, verbose_name='已刷脸认证'),
        ),
        migrations.CreateModel(
            name='FaceVerifySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certify_id', models.CharField(max_length=64, unique=True, verbose_name='认证ID')),
                ('outer_order_no', models.CharField(max_length=32, unique=True, verbose_name='业务流水号')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('passed', '已通过'), ('failed', '未通过')], default='pending', max_length=20, verbose_name='状态')),
                ('sub_code', models.CharField(blank=True, default='', max_length=20, verbose_name='结果码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verify_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '刷脸认证记录',
                'verbose_name_plural': '刷脸认证记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
