# Generated by Django 6.0.7 on 2026-07-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_face_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverifysession',
            name='id_card_number',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='faceverifysession',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名'),
        ),
    ]
