# Generated by Django 6.0.5 on 2026-07-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_identity_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '平台用户', 'verbose_name_plural': '平台用户'},
        ),
    ]
