# Generated by Django 6.0.7 on 2026-07-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('query_string', models.TextField(blank=True, default='', verbose_name='查询参数')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='状态码')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='耗时(ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='请求时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '前端请求日志',
                'verbose_name_plural': '前端请求日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
