# Generated by Django 6.0.7 on 2026-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_frontendrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendrequestlog',
            name='response_body',
            field=models.TextField(blank=True, default='', verbose_name='响应体'),
        ),
    ]
