# Generated by Django 6.0.7 on 2026-07-09 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='礼物名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='gifts/icons/', verbose_name='礼物图标')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格（元）')),
                ('heat_value', models.PositiveIntegerField(help_text='赠送后转换为候选人的热度', verbose_name='热度值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '礼物',
                'verbose_name_plural': '礼物',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('total_heat', models.PositiveIntegerField(verbose_name='总热度值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='赠送时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='candidates.candidate', verbose_name='接收候选人')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gifts.gift', verbose_name='礼物')),
            ],
            options={
                'verbose_name': '礼物赠送记录',
                'verbose_name_plural': '礼物赠送记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
