# Generated by Django 6.0.7 on 2026-07-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField(db_index=True, verbose_name='投票日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate', verbose_name='候选人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='投票用户')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'vote_date'], name='votes_vote_user_id_a73ee1_idx'), models.Index(fields=['candidate', 'vote_date'], name='votes_vote_candida_73a5da_idx')],
            },
        ),
    ]
