# Generated by Django 6.0.7 on 2026-07-09 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('number', models.PositiveIntegerField(help_text='参赛编号', unique=True, verbose_name='编号')),
                ('introduction', models.TextField(blank=True, default='', verbose_name='个人介绍')),
                ('avatar', models.ImageField(upload_to='candidates/avatars/', verbose_name='头像')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='投票数')),
                ('heat_score', models.PositiveIntegerField(default=0, help_text='投票+礼物转换的热度', verbose_name='热度值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否参赛')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidates/photos/', verbose_name='照片')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='candidates.candidate', verbose_name='候选人')),
            ],
            options={
                'verbose_name': '候选人照片',
                'verbose_name_plural': '候选人照片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
