# Generated by Django 6.0.5 on 2026-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='取消勾选即下架，前台列表/排行榜不再展示该候选人', verbose_name='是否参赛'),
        ),
    ]
