# Generated by Django 6.0.5 on 2026-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_registration_type_and_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='个人报名填写；团体报名可为空', null=True, verbose_name='身高(cm)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='个人报名填写；团体报名可为空', max_digits=5, null=True, verbose_name='体重(kg)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_url',
            field=models.URLField(blank=True, default='', help_text='作品展示链接，如视频/主页等', max_length=500, verbose_name='作品链接'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='个人报名填写；团体报名可为空', null=True, verbose_name='身高(cm)'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='个人报名填写；团体报名可为空', max_digits=5, null=True, verbose_name='体重(kg)'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='work_url',
            field=models.URLField(blank=True, default='', help_text='作品展示链接，如视频/主页等', max_length=500, verbose_name='作品链接'),
        ),
    ]
